version: '2.3'

services:
    frontend:
        build: ./dash
        depends_on:
            - tf_serving
            - redis
        ports:
            - 8050:8050
        volumes:
            - ./model:/usr/src/app/model

    redis:
        image: redis:alpine
        restart: always

    tf_serving:
        build:
            context: ./tf_serving
            dockerfile: Dockerfile
        volumes:
            - ./model:/models/object-detect/1
        ports:
            - 8085:8080
